headers = {
  'accept': 'application/json, text/plain, */*',
  'accept-language': 'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7',
  'cache-control': 'no-cache',
  'content-type': 'application/json',
  'downlink': '1.5',
  'origin': 'https://bot.true.world',
  'pragma': 'no-cache',
  'priority': 'u=1, i',
  'referer': 'https://bot.true.world/',
  'sec-ch-ua': '"Chromium";v="128", "Not;A=Brand";v="24", "Android WebView";v="128"',
  'sec-ch-ua-mobile': '?1',
  'sec-ch-ua-platform': '"Android"',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'same-site',
  'user-agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36',
  'x-requested-with': 'org.telegram.messenger',
}
